export struct FileUnit {
    name: string,
    owner: string,
    is_fold: bool,
    permission: int,
    file_path: string,
    mimetype: string,
    beselected: bool,
    image: image,
    sourcetype: int,
}

export struct FilterFun {
    filiter : string,
    selected: bool,
}

export global DefaultAsserts {
    in-out property <image> fileicon : @image-url("../assert/revolution.png");
}

export global GlobalFiles {
    in-out property <[FileUnit]> left: [];
    in-out property <[FileUnit]> right: [];
    in-out property <[FilterFun]> filiter :[];
    in-out property <bool> signalfile: false;
    in-out property <int> last-selected: -1 ;
    in-out property <string> current-path: "" ;
    in-out property <bool> is_select_fold: false ;
    in-out property <int> current-filiter:-1 ;
    in-out property <image> preview_image: DefaultAsserts.fileicon ;
    in-out property <string> preview_text: "" ;
}
