[package]
name = "xdg-desktop-portal-shana"
version = "0.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3", default-features = false, features = ["tokio", "url"] }
tokio = { version = "1.28.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4", features = ["serde"] }
serde_repr = "0.1"
toml = "0.7.4"
#once_cell = "1.17.1"
