[package]
name = "xdg-desktop-portal-shana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "2", default-features = false, features = ["tokio", "url"] }
tokio = { version = "1.18.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
filedialogshana = { path = "./crates/filedialogshana" }
shanatypes = { path = "./crates/shanatypes" }
