[package]
name = "xdg-desktop-portal-shana"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3", default-features = false, features = ["tokio", "url"] }
tokio = { version = "1.27.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = { version = "2.3", features = ["serde"] }
serde_repr = "0.1"
toml = "0.7.3"

