[package]
name = "shanatest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ashpd = { version = "0.4.0" }
async-std = { version = "1.12.0", features = ["async-attributes","attributes"] }
